Newsweek.com Homepage Clone Finished!
SlowKingV/using-bootstrap pull request #1
Opened 2019-12-20 21:51 UTC by SlowKingV

> This project requests students to build a replica of the news site [Newsweek.com](newsweek.com) using the Bootstrap framework.

## :tada: MILESTONES :tada:
- [x] Use **Semantic HTML** to build the page structure.
- [x] Download and set up ***[Bootstrap 4](https://getbootstrap.com/)*** into your project.
- [x] Use **CSS** to give proper styles to the content.
- [x] Use ***[Bootstrap 4](https://getbootstrap.com/)*** to align everything properly and make the page fully responsive!!!
- [x] Use **[W3C Validator](validator.w3.org/)** to find and fix any error inside the *index.html* file.
- [x] Set up a *linter* into the repo and solve any problem it might find.

***Everything is ready, waiting for approval   :thumbsup:***

2019-12-20 22:27 UTC, pelzolga123 commented on index.html
> +                            <h3 class="mb-0 py-md-3"><a href="">Canadian Mother Accused of Assaultin
It's better to delete comments.

2019-12-20 22:29 UTC, pelzolga123 commented on index.html
> +                            <h3 class="mb-0 py-md-3"><a href="">Canadian Mother Accused of Assaultin
It's better to delete comments.

2019-12-20 22:30 UTC, pelzolga123 requested changes
Bootstrap should be added using links.

2019-12-20 22:32 UTC, pelzolga123 commented on index.html
> +                            <h3 class="mb-0 py-md-3"><a href="">Canadian Mother Accused of Assaultin
It's better to delete comments.

2019-12-20 22:32 UTC, pelzolga123 commented
## Hi Diego! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing! You did very good job!
### Kudos for most descriptive README file I've seen so far :100: 

I see only one thin that needs correction:
* [ ] Html should reference Bootstrap CSS file like [this website](https://getbootstrap.com/docs/4.3/getting-started/introduction/#css) shows. Right now you just add it manually. [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_requirement.png)  

### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2019-12-21 00:12 UTC, SlowKingV commented
### I got rid of all the local Bootstrap files and replaced the links for the ones on the page :+1:

2019-12-21 04:58 UTC, izaiasneto4 commented
### Hi @SlowKingV :wave: 

Nice job implementing the requested changes! Project approved! :+1: 

TSE: Izaias Neto

2019-12-21 05:35 UTC, merged